FROM ruby:2.6.0-preview2-alpine3.7

RUN apk --no-cache add tzdata nodejs postgresql postgresql-dev icu-dev g++ make cmake

RUN cp /usr/share/zoneinfo/Asia/Tokyo /etc/localtime

WORKDIR /app

ENTRYPOINT ["bin/docker-setup"]
CMD "bin/rails about"
